### ISSUE TITLE
 Error in DataExport Plugin: array_diff(): Argument #1 ($array) must be of type array, bool given

### ISSUE THREAD

**Issue by xjy1592922966** [jorgeuos/DataExport#2]
**Issue Description:**
I encountered an issue while using the DataExport plugin in Matomo. When attempting to export data, I received the following error message:
"The following error just broke Matomo (v5.0.3):
array_diff(): Argument #1 ($array) must be of type array, bool given
in /www/wwwroot/10.0.200.91/plugins/DataExport/Services/FileService.php line 219"

**Technical Details:**
- Programming Language/Framework: PHP 8.2, Matomo 5.0.3
- Relevant Code Snippet: N/A
- Expected Result: Successful data export
- Actual Result: Error message as described above

**Attempted Solutions:**
1. Reinstalled the plugin, cleared PHP cache, and restarted the server.
2. Upgraded Matomo to the latest version, reinstalled the plugin, and cleared PHP cache.

**Environment Information:**
Operating System: CentOS 7.6.1810

**Additional Remarks:**
I haven't performed any custom development on Matomo. Currently, the data tracking is functioning correctly, but I encounter this error. I apologize for any inaccuracies in the translation as it was done using translation software. Please note that the translated content may not be entirely accurate. If there are any errors or missing crucial information, please let me know, and I'll be happy to provide further clarification.

thanks!

**Comment by xjy1592922966** [comment]
![image](https://github.com/jorgeuos/DataExport/assets/17585645/687d5712-4a48-483d-883a-8d6a1edaf208)

**Comment by xjy1592922966** [comment]
Issue Resolved - Missing Directory Caused the Error

**Solution:**
After further investigation, I found that the issue was caused by the absence of the "matomo/tmp/de_backups" directory in my Matomo project. I have resolved the problem by creating the necessary directory. 

Thank you for your excellent project!

问题已解决-缺少目录导致错误

解决方案：
经过进一步调查，我发现问题是由于我的Matomo项目中缺少“matomo/tmp/de_backups”目录所致。我通过创建必要的目录解决了这个问题。

感谢您的优秀项目！

**Comment by jorgeuos** [comment]
Oh, ok! Nice!
I should probably add a check for that.
Thank you for letting me now!
